name: Marcus Stenbeck's Masters Thesis Project
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
permalink: :categories/:title/
url: http://marcusstenbeck.com/exjobb
